
version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'compose-demo-product'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  web2:
    build:
      context: web2
    restart: always
    environment:
      EMAIL_SERVER_PORT: 'email_service:50053'
      PRODUCT_SERVER_PORT: 'product_service:50055'
      FLASK_ENV: 'development'
    volumes:
      - .:/code
    ports:
      - "5001:5000"
    command: >
      sh -c "cd web2 &&
             python3 app.py"

  product_service:
    build:
      context: product_service
      dockerfile: Dockerfile
    restart: always
    environment:
      PRODUCT_SERVICE_DB_HOST: 'mysql:3306'
      PRODUCT_SERVICE_DB_NAME: 'compose-demo-product'
      PRODUCT_SERVICE_DB_USER: 'root'
      PRODUCT_SERVICE_DB_PASSWORD: ''
    volumes:
      - .:/code
    ports:
      - "50055:50055"
    depends_on:
      - mysql
    command: >
      sh -c "cd product_service &&
             python3 serve.py"

  email_service:
    build:
      context: email_service
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "50053:50053"
    command: >
      sh -c "cd email_service &&
             python3 serve.py"

volumes:
  my-db:
