# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email.proto',
  package='core.email',
  syntax='proto3',
  serialized_options=_b('H\001'),
  serialized_pb=_b('\n\x0b\x65mail.proto\x12\ncore.email\"\x0e\n\x0c\x45mptyRequest\"!\n\x0fOperationStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2M\n\x05\x45mail\x12\x44\n\tSendEmail\x12\x18.core.email.EmptyRequest\x1a\x1b.core.email.OperationStatus\"\x00\x42\x02H\x01\x62\x06proto3')
)




_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='core.email.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=41,
)


_OPERATIONSTATUS = _descriptor.Descriptor(
  name='OperationStatus',
  full_name='core.email.OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='core.email.OperationStatus.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['OperationStatus'] = _OPERATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'email_pb2'
  # @@protoc_insertion_point(class_scope:core.email.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONSTATUS,
  __module__ = 'email_pb2'
  # @@protoc_insertion_point(class_scope:core.email.OperationStatus)
  ))
_sym_db.RegisterMessage(OperationStatus)


DESCRIPTOR._options = None

_EMAIL = _descriptor.ServiceDescriptor(
  name='Email',
  full_name='core.email.Email',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendEmail',
    full_name='core.email.Email.SendEmail',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_OPERATIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAIL)

DESCRIPTOR.services_by_name['Email'] = _EMAIL

# @@protoc_insertion_point(module_scope)
