# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import email_pb2 as email__pb2


class EmailStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendEmail = channel.unary_unary(
        '/core.email.Email/SendEmail',
        request_serializer=email__pb2.EmptyRequest.SerializeToString,
        response_deserializer=email__pb2.OperationStatus.FromString,
        )


class EmailServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmailServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendEmail,
          request_deserializer=email__pb2.EmptyRequest.FromString,
          response_serializer=email__pb2.OperationStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.email.Email', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
