# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import product_pb2 as product__pb2


class ProductAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllProducts = channel.unary_unary(
        '/core.product.ProductAPI/GetAllProducts',
        request_serializer=product__pb2.EmptyRequest.SerializeToString,
        response_deserializer=product__pb2.Products.FromString,
        )


class ProductAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllProducts': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllProducts,
          request_deserializer=product__pb2.EmptyRequest.FromString,
          response_serializer=product__pb2.Products.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.product.ProductAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
